baseURL       = "https://hong-kong-districts-info.github.io/"
languageCode  = "en-us"
title         = "Hong Kong Districts Info"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home / 主頁"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About / 關於"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Projects / 項目"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "DCs / 區議員"
    url     = "dc"
    weight  = 4
  [[menu.nav]]
    name    = "Blog / 博客"
    url     = "blog"
    weight  = 5
  [[menu.nav]]
    name    = "Get in touch / 聯絡我們"
    url     = "contact"
    weight  = 6

# Site Params
[params]
  logo = "images/logo-nonhex.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Hong Kong Districts Info"
  author = "Hong Kong Districts Info"
  # Google Analytics
  googleAnalitycsID = "UA-173737339-2"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/output.gif"
    heading               = "We code for Hong Kong"
    tagline               = "EMPOWERING HONG KONG THROUGH CODING"
    primary_button        = "See Our Projects"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT PROJECTS"
    subtitle  = "Projects to empower Hong Kong"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = ""
      phone   = ""
      email   = "hkdistricts.info@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Us"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "District Councillors"
          url  = "dc"          
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/Hong-Kong-Districts-Info/"
      # Footer Service
      [params.footer.service]
        title       = "We empower people:"
        description = "by making information easily accessible and removing the friction in civic participation."

[taxonomies]
  tag = "tags"
  category = "categories"
  languages = "languages"
